 -- Use the true_false_quiz database
 USE true_false_quiz;
 
 -- drop existing questions table if it already exists
 drop table if exists questions;
 
 -- Create the table questions with 3 columns:
 -- QuestionID - primary key giving each question a unique ID 
 -- Question - the question itself
 -- Answer - boolean: true or false
 
CREATE TABLE questions (
	QuestionID int not null auto_increment,
    Question varchar(500),
    Answer boolean,
    CONSTRAINT PK_Questions PRIMARY KEY(QuestionID)
);

-- Insert the questions into the database
-- QuestionID auto increments for each entry

INSERT INTO Questions (Question, Answer)
VALUES ("The femur is the longest bone in the human body", True),
	   ("The element in the periodic table with atomic number 1 is nitrogen", False),
       ("Helium is a noble gas", True),
       ("The language with the most native speakers is English", False),
       ("Spanish has more native speakers than English", True),
       ("70 books make up the Bible", False),
       ("The largest country by land area is Russia", True),
	   ("The largest country by population is the USA", False),
	   ("54 countries make up Africa", True),
	   ("There are 9 planets in the solar system", False),
	   ("Mars has 2 moons", True),
	   ("Spanish is the most spoken language in Brazil", False),
	   ("The average height of a male adult Asian elephant is 2.8m", True),
	   ("There are two parts of the body that can't heal themselves", False),
	   ("Alliumphobia is a fear of garlic", True),
	   ("‘A’ is the most common letter in the English alphabet", False),
       ("Clapham Junction is the busiest station in the UK for interchanges", True),
       ("Monaco is the smallest country in the world", False),
       ("Alaska is the biggest American state in square miles", True),
       ("K is worth 4 points in Scrabble", False),
       ("There are 8 different blood groups", True),
       ("The moon is wider than Australia", False),
	   ("Venus is the hottest planet in the solar system", True),
	   ("W is worth 6 points in Scrabble", False),
	   ("Fish cannot blink", True),
       ("Four countries border Switzerland", False),
       ("When the two numbers on opposite sides of a dice are added together it always equals 7", True),
       ("In a regular deck of cards, all kings have a mustache", False),
	   ("Jail is the most landed on Monopoly Space", True),
       ("Among the letters of the alphabet, only the letter Z is not included in the periodic table", False),
       ("The mosquito has a record for killing more people than any other species in written history", True),
       ("An angle greater than 90 degrees is reflex", False),
       ("Angles in a triangle add up to 180 degrees", True),
       ("A shape with 13 sides is called a hendecagon", False),
       ("1 mile = 1.6km", True),
       ("20 degrees Celsius is 80 degrees in Fahrenheit", False),
       ("Displacement is a vector quantity", True),
	   ("Velocity is a scalar quantity", False),
       ("In the Tokyo Olympics 2020, USA won the most gold medals", True),
       ("Light is an example of a mechanical wave", False),
       ("The greater the amplitude of a sound wave, the louder it is ", True),
       ("There is one path for electricity to flow in a parallel circuit", False),
       ("An ammeter is used to measure current", True),
       ("A voltmeter should be connected in series with a circuit", False),
	   ("10 in binary is 2 in decimal", True),
       ("An interpreter compiles a program in one go", False),
       ("The main memory in a computer is volatile", True),
       ("Microsoft Word is an example of computer hardware", False),
       ("In logic, the symbol ‘^’ denotes ‘or’", True),
       ("The hexadecimal number system contains digits from 1 - 15", False),
       ("The Octal number system contains digits from 0 - 7", True),
       ("The char data type can store 10 alphanumeric characters", False),
       ("You can make objects of a final class", True),
       ("Abstract classes cannot have constructors", False),
       ("The <img> HTML element does not require a closing tag", True),
       ("The head section of HTML is visible to the user", False),
       ("HTML stands for Hyper Text Markup Language", True),
       ("A lossy format means the file does not get rid of data and lose quality", False),
       ("SQL stands for Structured Query Language", True),
       ("The switch statement in Java must end with the ‘default’ case", False),
       ("Python is a scripting language", True),
       ("Constructor overloading is not possible in Java", False),
       ("In Java, for an instance method or a constructor, 'this' is a reference to the current object", True),
       ("Saturn is the only planet in the solar system to have rings", False),
       ("A year on Venus is about 225 Earth days", True),
       ("Mount Everest is the tallest mountain in the solar system", False),
       ("Ions are atoms that have gained or lost electrons", True),
       ("A substance with pH 10 is an acid", False),
       ("A substance with pH 9 is an alkali", True),
       ("All cells have a cell wall", False),
       ("All cells have a cell membrane", True),
       ("The nucleus controls the substances that enter or exit a cell", False),
       ("The river Severn flows through both England and Wales", True),
       ("France and Slovenia share a border", False),
       ("Stonehenge is located less than 10 miles from Salisbury", True),
       ("Belarus became independent in 2001", False),
       ("Less than 4 million people live in Paris", True),
       ("Hadrian’s border is located on the border between England and Wales", False),
       ("The original London Bridge can be found in Arizona", True),
       ("The Niger river is in eastern Africa", False),
       ("Yuri Gagarin became the first human in space in 1961", True),
       ("Henry VIII had 5 wives", False),
       ("French used to be the official language of England", True),
       ("The UK has no land borders with other countries", False),
       ("The dragon is the national animal of Wales", True),
       ("The Titanic was built in Liverpool", False),
       ("There are more than 24 time zones across the world", True),
       ("39% of the world’s forests are in Canada",	False),
       ("Every giant panda around the world is the property of the government of China", True),
       ("All reptiles are completely deaf",	False),
       ("Skin has up to 1000 species of bacteria", True),
       ("Octopuses have 8 hearts", False),
       ("The Statue of Liberty was a gift from France",	True),
       ("A woman has walked on the moon", False),
       ("The blue whale is the biggest animal to have ever lived", True),
       ("A monkey was the first non-human to go into space", False),
       ("Venezuela is home to the world’s highest waterfall", True),
       ("The Chunnel between England and France is 25 miles long", False),
       ("The average human sneeze can be clocked at 100 miles an hour",	True),
       ("Human skin regenerates every fortnight", False),
       ("The song “We Don’t Talk About Bruno” from Encanto is the first Disney song to hit #1 on the Billboard Hot 100 chart in 29 years", True),
       ("Pinocchio was the first animated, full-color Walt Disney feature film", False),
       ("Toy Story was Pixar’s first movie", True),
       ("Cheesecake comes from Italy", False),
       ("Dumbo is the shortest Disney film", True),
	   ("French fries originated from France", False),
       ("Mushrooms are the 2nd most popular pizza topping in the USA", True),
       ("The Chinese New Year is celebrated on the same day every year", False),
       ("The New York Marathon is the largest in the world", True),
	   ("Three strikes in a row in bowling is called a chicken", False),
       ("The Harry Potter film “Chamber of Secrets”, is the longest film of the Harry Potter movies", True),
       ("People who have chiclephobia are afraid of cats", False),
       ("If you cry in space the tears just stick to your face", True),
       ("Pepsi was the first soft drink to be enjoyed in outer space", False),
       ("Humans can distinguish between over a trillion different smells",	True),
       ("The American Civil War ended in 1776",  False),
       ("The Spanish national anthem has no words",	True),
       ("The lungs are the body’s largest organ", False),
       ("Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid of Giza",	True),
       ("There are five red stripes in the United States flag",	False);

-- Select all values from the table to check the table
select * from questions;